spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&autoReconnection=true&useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver